.PHONY: all
all:
	cd exam_txt && $(MAKE) all
	cd exam_md && $(MAKE) all
	cd exam_latex && $(MAKE) all

.PHONY: clean
clean:
	cd exam_txt && $(MAKE) clean
	cd exam_md && $(MAKE) clean
	cd exam_latex && $(MAKE) clean

.PHONY: install
install:
	cd exam_txt && $(MAKE) install
	cd exam_md && $(MAKE) install
	cd exam_latex && $(MAKE) install

